data:
  raw_path: "data/raw/clothing-dataset-small"
  num_classes: 10

model:
  base_model: "xception"
  input_shape: [299, 299, 3]
  learning_rate: 0.001
  inner_layer_size: 100
  dropout_rate: 0.5

training:
  batch_size: 32
  epochs: 20